CREATE EXTENSION IF NOT EXISTS CUBE;

CREATE TABLE IF NOT EXISTS "user" (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    username VARCHAR NOT NULL UNIQUE,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS identity (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    avatar VARCHAR,
    UNIQUE (first_name, last_name)
);

CREATE TABLE IF NOT EXISTS face_encoding (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    identity_id UUID NOT NULL REFERENCES identity,
    vec_low DOUBLE PRECISION ARRAY NOT NULL,
    vec_high DOUBLE PRECISION ARRAY NOT NULL
);

CREATE TABLE IF NOT EXISTS camera (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    label VARCHAR NOT NULL,
    url VARCHAR NOT NULL UNIQUE,
    username VARCHAR,
    password VARCHAR
);

CREATE TABLE IF NOT EXISTS query (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS suggestion (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    query_id UUID NOT NULL REFERENCES query,
    rect INTEGER ARRAY NOT NULL CHECK (ARRAY_LENGTH(rect, 1) = 4),
    identity_id UUID REFERENCES identity,
    score DOUBLE PRECISION,
    vec_low DOUBLE PRECISION ARRAY NOT NULL,
    vec_high DOUBLE PRECISION ARRAY NOT NULL
);
